output "ssh_key_name" {
  value       = aws_key_pair.ssh_key[*].key_name
  description = "The name of the SSH key generated by Terraform."
}

output "server_using_custom_palworldsettingsini" {
  value       = var.use_custom_palworldsettings
  description = "Is the server using custom palworldsettings.ini."
}

output "custom_ini_s3_bucket_name" {
  value       = aws_s3_bucket.palworld[*].id
  description = "The ID of the S3 bucket that was created if use custom ini with s3 was configured."
}

output "custom_palworldsettings_file_name" {
  value       = aws_s3_object.palworldsettings[*].key
  description = "The custom palworldsettings file name that was uploaded to s3 if use custom GUS ini with s3 was configured."
}


output "palworldsettings_s3_content" {
  value       = aws_s3_object.palworldsettings[*].content
  description = "The contents of the palworldsettings.ini ( experimental )."
}


output "palworldsettings_s3_bucket" {
  value       = aws_s3_object.palworldsettings[*].bucket
  description = "The download URI of the palworldsettings.ini from s3 ( experimental )."
}

output "palworld_server_public_port" {
  value       = var.public_port
  description = "The public port to connect to the Palworld sevrer on."
}

output "palworld_server_public_ip" {
  value       = aws_eip.palworld_server_ip.public_ip
  description = "The public IP address of the Palworld server to connect on."
}

output "session_manager_enabled" {
  value       = var.enable_session_manager
  description = "Is AWS SSM Session Manager enabled or not."
}
